development:
  access_key_id: 'ACCESS_KEY'
  secret_access_key: 'SECRET_KEY'
  use_ssl: false
  bucket_name: 'development_bucket'

production:
  access_key_id: 'ACCESS_KEY'
  secret_access_key: 'SECRET_KEY'
  use_ssl: false
  bucket_name: 'production_bucket'
